SELECT * FROM Funcionario
SELECT * FROM Login
SELECT * FROM Quarto
SELECT * FROM Reserva
SELECT * FROM Tipo_Quarto

SELECT Nome,* FROM FUNCIONARIO
WHERE EMAIL like '%@gmail%' 

SELECT NOME, YEAR(DataAdmissao) AS "ADMISSÃO" FROM FUNCIONARIO

SELECT *, DATEDIFF(YEAR,DataAdmissao,GETDATE()) AS TEMPO FROM FUNCIONARIO
WHERE idFuncionario = 1